import sqlite3

import os
import random

films = [
    {
        'id': 1,
        'titre': 'Avatar',
        'annee': 2009,
        'duration': 162,
        'resume': "Un marine paraplégique envoyé sur la lune Pandora pour une mission unique est tiraillé entre suivre ses ordres et protéger le monde qu'il considère le sien.",
        'anecdotes': "Premier film à dépasser 2 milliards de dollars.",
        'distribution': "Sam Worthington, Zoe Saldana",
        'categorie': "Science-fiction",
        'distributeurs': "20th Century Fox",
        'commentaires': "Effets spéciaux révolutionnaires.",
        'bande_annonce': "https://www.youtube.com/watch?v=5PSNL1qE6VY",
        'note_globale': 8.5,
        'note_violence': 3.0,
        'note_sexe': 2.0,
        'note_humour': 2.0,
        'note_peur': 2.0,
        'note_drogue': 0.0,
        'note_utilisateur': 0.0,
        'age_interdit': 0.0,
        'age_recommande': 12.0,
        'realisateur': 'James Cameron',
        'scenariste': 'James Cameron',
    },
    {
        'id': 2,
        'titre': 'Avengers: Endgame',
        'annee': 2019,
        'duration': 181,
        'resume': "Les Avengers affrontent Thanos pour sauver l'univers.",
        'anecdotes': "Climax de 22 films Marvel.",
        'distribution': "Robert Downey Jr., Chris Evans",
        'categorie': "Action|Super-héros",
        'distributeurs': "Marvel Studios",
        'commentaires': "Émotion et action au rendez-vous.",
        'bande_annonce': "https://www.youtube.com/watch?v=TcMBFSGVi1c",
        'note_globale': 8.7,
        'note_violence': 4.0,
        'note_sexe': 1.0,
        'note_humour': 3.0,
        'note_peur': 2.0,
        'note_drogue': 0.0,
        'note_utilisateur': 0.0,
        'age_interdit': 0.0,
        'age_recommande': 12.0,
        'realisateur': 'Anthony Russo, Joe Russo',
        'scenariste': 'Christopher Markus, Stephen McFeely',
    },
    {
        'id': 3,
        'titre': 'Titanic',
        'annee': 1997,
        'duration': 195,
        'resume': "Une romance tragique à bord du Titanic.",
        'anecdotes': "Oscars du meilleur film et réalisateur.",
        'distribution': "Leonardo DiCaprio, Kate Winslet",
        'categorie': "Drame|Romance",
        'distributeurs': "Paramount Pictures",
        'commentaires': "Film culte de James Cameron.",
        'bande_annonce': "https://www.youtube.com/watch?v=kVrqfYjkTdQ",
        'note_globale': 9.0,
        'note_violence': 2.0,
        'note_sexe': 3.0,
        'note_humour': 2.0,
        'note_peur': 2.0,
        'note_drogue': 1.0,
        'note_utilisateur': 0.0,
        'age_interdit': 0.0,
        'age_recommande': 10.0,
        'realisateur': 'James Cameron',
        'scenariste': 'James Cameron',
    },
    {
        'id': 4,
        'titre': 'Star Wars: Le Réveil de la Force',
        'annee': 2015,
        'duration': 138,
        'resume': "La Résistance affronte le Premier Ordre.",
        'anecdotes': "Retour de la saga après 10 ans.",
        'distribution': "Daisy Ridley, John Boyega",
        'categorie': "Science-fiction",
        'distributeurs': "Lucasfilm",
        'commentaires': "Nouveau souffle pour Star Wars.",
        'bande_annonce': "https://www.youtube.com/watch?v=sGbxmsDFVnE",
        'note_globale': 7.8,
        'note_violence': 3.0,
        'note_sexe': 0.5,
        'note_humour': 2.5,
        'note_peur': 2.0,
        'note_drogue': 0.0,
        'note_utilisateur': 0.0,
        'age_interdit': 0.0,
        'age_recommande': 10.0,
        'realisateur': 'J.J. Abrams',
        'scenariste': 'Lawrence Kasdan, J.J. Abrams, Michael Arndt',
    },
    {
        'id': 5,
        'titre': 'Avengers: Infinity War',
        'annee': 2018,
        'duration': 149,
        'resume': "Les Avengers affrontent Thanos pour la première fois.",
        'anecdotes': "Première partie du final Marvel.",
        'distribution': "Robert Downey Jr., Chris Hemsworth",
        'categorie': "Action|Super-héros",
        'distributeurs': "Marvel Studios",
        'commentaires': "Choc et suspense.",
        'bande_annonce': "https://www.youtube.com/watch?v=6ZfuNTqbHE8",
        'note_globale': 8.4,
        'note_violence': 4.0,
        'note_sexe': 1.0,
        'note_humour': 3.0,
        'note_peur': 2.5,
        'note_drogue': 0.0,
        'note_utilisateur': 0.0,
        'age_interdit': 0.0,
        'age_recommande': 12.0,
        'realisateur': 'Anthony Russo, Joe Russo',
        'scenariste': 'Christopher Markus, Stephen McFeely',
    },
    {
        'id': 6,
        'titre': 'Jurassic World',
        'annee': 2015,
        'duration': 124,
        'resume': "Un nouveau parc de dinosaures ouvre ses portes.",
        'anecdotes': "Retour de la franchise culte.",
        'distribution': "Chris Pratt, Bryce Dallas Howard",
        'categorie': "Aventure|Science-fiction",
        'distributeurs': "Universal Pictures",
        'commentaires': "Dinosaures et action.",
        'bande_annonce': "https://www.youtube.com/watch?v=RFinNxS5KN4",
        'note_globale': 7.2,
        'note_violence': 3.5,
        'note_sexe': 0.5,
        'note_humour': 2.0,
        'note_peur': 2.5,
        'note_drogue': 0.0,
        'note_utilisateur': 0.0,
        'age_interdit': 0.0,
        'age_recommande': 10.0,
        'realisateur': 'Colin Trevorrow',
        'scenariste': 'Rick Jaffa, Amanda Silver, Derek Connolly, Colin Trevorrow',
    },
    {
        'id': 7,
        'titre': 'Le Roi Lion',
        'annee': 2019,
        'duration': 118,
        'resume': "Le jeune Simba doit reprendre sa place de roi.",
        'anecdotes': "Remake en images de synthèse.",
        'distribution': "Donald Glover, Beyoncé",
        'categorie': "Animation|Famille",
        'distributeurs': "Walt Disney Studios",
        'commentaires': "Classique revisité.",
        'bande_annonce': "https://www.youtube.com/watch?v=7TavVZMewpY",
        'note_globale': 7.0,
        'note_violence': 2.0,
        'note_sexe': 0.0,
        'note_humour': 2.5,
        'note_peur': 1.5,
        'note_drogue': 0.0,
        'note_utilisateur': 0.0,
        'age_interdit': 0.0,
        'age_recommande': 6.0,
        'realisateur': 'Jon Favreau',
        'scenariste': 'Jeff Nathanson',
    },
    {
        'id': 8,
        'titre': 'Fast & Furious 7',
        'annee': 2015,
        'duration': 137,
        'resume': "L'équipe affronte un nouvel ennemi et rend hommage à Paul Walker.",
        'anecdotes': "Dernier film avec Paul Walker.",
        'distribution': "Vin Diesel, Paul Walker",
        'categorie': "Action",
        'distributeurs': "Universal Pictures",
        'commentaires': "Courses et émotions.",
        'bande_annonce': "https://www.youtube.com/watch?v=Skpu5HaVkOc",
        'note_globale': 7.1,
        'note_violence': 4.0,
        'note_sexe': 1.5,
        'note_humour': 2.0,
        'note_peur': 1.5,
        'note_drogue': 0.0,
        'note_utilisateur': 0.0,
        'age_interdit': 0.0,
        'age_recommande': 12.0,
        'realisateur': 'James Wan',
        'scenariste': 'Chris Morgan',
    },
    {
        'id': 9,
        'titre': 'La Reine des Neiges II',
        'annee': 2019,
        'duration': 103,
        'resume': "Elsa et Anna partent à la découverte de l'origine des pouvoirs d'Elsa.",
        'anecdotes': "Suite du succès mondial.",
        'distribution': "Kristen Bell, Idina Menzel",
        'categorie': "Animation|Famille",
        'distributeurs': "Walt Disney Studios",
        'commentaires': "Chansons inoubliables.",
        'bande_annonce': "https://www.youtube.com/watch?v=Zi4LMpSDccc",
        'note_globale': 6.9,
        'note_violence': 1.0,
        'note_sexe': 0.0,
        'note_humour': 2.5,
        'note_peur': 1.0,
        'note_drogue': 0.0,
        'note_utilisateur': 0.0,
        'age_interdit': 0.0,
        'age_recommande': 6.0,
        'realisateur': 'Chris Buck, Jennifer Lee',
        'scenariste': 'Jennifer Lee',
    },
    {
        'id': 10,
        'titre': 'La Belle et la Bête',
        'annee': 2017,
        'duration': 129,
        'resume': "Une jeune femme tombe amoureuse d'une bête.",
        'anecdotes': "Adaptation live du classique Disney.",
        'distribution': "Emma Watson, Dan Stevens",
        'categorie': "Fantastique|Romance",
        'distributeurs': "Walt Disney Studios",
        'commentaires': "Magie et romance.",
        'bande_annonce': "https://www.youtube.com/watch?v=e3Nl_TCQXuw",
        'note_globale': 7.1,
        'note_violence': 1.5,
        'note_sexe': 0.5,
        'note_humour': 2.0,
        'note_peur': 1.0,
        'note_drogue': 0.0,
        'note_utilisateur': 0.0,
        'age_interdit': 0.0,
        'age_recommande': 6.0,
        'realisateur': 'Bill Condon',
        'scenariste': 'Stephen Chbosky, Evan Spiliotopoulos',
    },
    {
        'id': 11,
        'titre': 'Les Indestructibles 2',
        'annee': 2018,
        'resume': "La famille de super-héros reprend du service.",
        'anecdotes': "Suite très attendue.",
        'distribution': "Craig T. Nelson, Holly Hunter",
        'categorie': "Animation|Action",
        'distributeurs': "Pixar Animation Studios",
        'commentaires': "Humour et action.",
        'bande_annonce': "https://www.youtube.com/watch?v=i5qOzqD9Rms",
        'note_globale': 7.6,
        'note_violence': 2.0,
        'note_sexe': 0.0,
        'note_humour': 3.5,
        'note_peur': 1.0,
        'age_recommande': '6',
    },
    {
        'id': 12,
        'titre': 'Iron Man 3',
        'annee': 2013,
        'resume': "Tony Stark affronte un nouvel ennemi, le Mandarin.",
        'anecdotes': "Troisième opus de la saga Iron Man.",
        'distribution': "Robert Downey Jr., Gwyneth Paltrow",
        'categorie': "Action|Super-héros",
        'distributeurs': "Marvel Studios",
        'commentaires': "Humour et action.",
        'bande_annonce': "https://www.youtube.com/watch?v=Ke1Y3P9D0Bc",
        'note_globale': 7.2,
        'note_violence': 3.0,
        'note_sexe': 1.0,
        'note_humour': 3.0,
        'note_peur': 1.5,
        'age_recommande': '10',
    },
    {
        'id': 13,
        'titre': 'Minions',
        'annee': 2015,
        'resume': "Les Minions cherchent un nouveau maître.",
        'anecdotes': "Spin-off de Moi, Moche et Méchant.",
        'distribution': "Sandra Bullock, Pierre Coffin",
        'categorie': "Animation|Comédie",
        'distributeurs': "Universal Pictures",
        'commentaires': "Humour pour petits et grands.",
        'bande_annonce': "https://www.youtube.com/watch?v=eisKxhjBnZ0",
        'note_globale': 6.4,
        'note_violence': 1.0,
        'note_sexe': 0.0,
        'note_humour': 4.0,
        'note_peur': 0.5,
        'age_recommande': '6',
    },
    {
        'id': 14,
        'titre': 'Captain America: Civil War',
        'annee': 2016,
        'resume': "Les Avengers se divisent sur la question du contrôle gouvernemental.",
        'anecdotes': "Conflit majeur entre super-héros.",
        'distribution': "Chris Evans, Robert Downey Jr.",
        'categorie': "Action|Super-héros",
        'distributeurs': "Marvel Studios",
        'commentaires': "Action et dilemmes moraux.",
        'bande_annonce': "https://www.youtube.com/watch?v=dKrVegVI0Us",
        'note_globale': 7.8,
        'note_violence': 3.5,
        'note_sexe': 0.5,
        'note_humour': 2.5,
        'note_peur': 1.5,
        'age_recommande': '10',
    },
    {
        'id': 15,
        'titre': 'La Belle et la Bête (1991)',
        'annee': 1991,
        'resume': "Belle découvre la bonté cachée de la Bête.",
        'anecdotes': "Premier film d'animation nommé à l'Oscar du meilleur film.",
        'distribution': "Paige O'Hara, Robby Benson",
        'categorie': "Animation|Romance",
        'distributeurs': "Walt Disney Studios",
        'commentaires': "Classique Disney.",
        'bande_annonce': "https://www.youtube.com/watch?v=tRlzmyveDHE",
        'note_globale': 8.0,
        'note_violence': 1.0,
        'note_sexe': 0.0,
        'note_humour': 2.5,
        'note_peur': 1.0,
        'age_recommande': '6',
    },
    {
        'id': 16,
        'titre': 'La Reine des Neiges',
        'annee': 2013,
        'resume': "Elsa doit apprendre à contrôler ses pouvoirs.",
        'anecdotes': "Chanson 'Libérée, délivrée' mondialement connue.",
        'distribution': "Kristen Bell, Idina Menzel",
        'categorie': "Animation|Famille",
        'distributeurs': "Walt Disney Studios",
        'commentaires': "Phénomène mondial.",
        'bande_annonce': "https://www.youtube.com/watch?v=TbQm5doF_Uc",
        'note_globale': 7.5,
        'note_violence': 1.0,
        'note_sexe': 0.0,
        'note_humour': 3.0,
        'note_peur': 1.0,
        'age_recommande': '6',
    },
    {
        'id': 17,
        'titre': 'Les Dents de la Mer',
        'annee': 1975,
        'resume': "Un grand requin blanc terrorise une station balnéaire.",
        'anecdotes': "Premier blockbuster de l'histoire.",
        'distribution': "Roy Scheider, Robert Shaw",
        'categorie': "Thriller|Horreur",
        'distributeurs': "Universal Pictures",
        'commentaires': "Suspense et frissons.",
        'bande_annonce': "https://www.youtube.com/watch?v=U1fu_sA7XhE",
        'note_globale': 8.0,
        'note_violence': 3.5,
        'note_sexe': 0.5,
        'note_humour': 1.0,
        'note_peur': 4.0,
        'age_recommande': '12',
    },
    {
        'id': 18,
        'titre': 'Harry Potter à l\'école des sorciers',
        'annee': 2001,
        'resume': "Harry découvre qu'il est un sorcier.",
        'anecdotes': "Début d'une saga culte.",
        'distribution': "Daniel Radcliffe, Emma Watson",
        'categorie': "Fantastique|Aventure",
        'distributeurs': "Warner Bros.",
        'commentaires': "Magie et amitié.",
        'bande_annonce': "https://www.youtube.com/watch?v=VyHV0BRtdxo",
        'note_globale': 7.6,
        'note_violence': 2.0,
        'note_sexe': 0.0,
        'note_humour': 2.5,
        'note_peur': 2.0,
        'age_recommande': '8',
    },
    {
        'id': 19,
        'titre': 'Black Panther',
        'annee': 2018,
        'resume': "T'Challa devient roi du Wakanda.",
        'anecdotes': "Premier film Marvel nommé aux Oscars.",
        'distribution': "Chadwick Boseman, Michael B. Jordan",
        'categorie': "Action|Super-héros",
        'distributeurs': "Marvel Studios",
        'commentaires': "Célébration de la culture africaine.",
        'bande_annonce': "https://www.youtube.com/watch?v=xjDjIWPwcPU",
        'note_globale': 7.3,
        'note_violence': 3.0,
        'note_sexe': 0.5,
        'note_humour': 2.0,
        'note_peur': 1.5,
        'age_recommande': '10',
    },
    {
        'id': 20,
        'titre': 'Transformers: Le côté obscur de la Lune',
        'annee': 2011,
        'resume': "Les Autobots affrontent les Decepticons sur la Lune.",
        'anecdotes': "Troisième opus de la saga Transformers.",
        'distribution': "Shia LaBeouf, Rosie Huntington-Whiteley",
        'categorie': "Action|Science-fiction",
        'distributeurs': "Paramount Pictures",
        'commentaires': "Effets spéciaux spectaculaires.",
        'bande_annonce': "https://www.youtube.com/watch?v=3H8bnKdf654",
        'note_globale': 6.2,
        'note_violence': 3.5,
        'note_sexe': 1.0,
        'note_humour': 2.0,
        'note_peur': 2.0,
        'age_recommande': '10',
    },
]

conn = sqlite3.connect('movies.db')
c = conn.cursor()
for film in films:
    # Nettoyage et ajout des notes demandées
    film.pop('note_humour', None)
    film.pop('note_peur', None)
    # Ajout de note_complexite et note_language si manquantes ou forcées aléatoires
    film['note_complexite'] = random.choice([None, round(random.uniform(0, 5), 1)])
    film['note_language'] = random.choice([None, round(random.uniform(0, 5), 1)])
    img_path = f"assets/cover/{film['id']}.jpg"
    c.execute('''INSERT INTO films (
        titre, resume, anecdotes, distribution, categorie, annee, distributeurs, commentaires, bande_annonce,
        note_globale, note_violence, note_sexe, note_complexite, note_language, note_drogue, note_utilisateur,
        age_interdit, age_recommande, realisateur, scenariste, duration, image_url
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)''',
        (
            film['titre'], film['resume'], film['anecdotes'], film['distribution'], film['categorie'], film['annee'],
            film['distributeurs'], film['commentaires'], film['bande_annonce'], film['note_globale'], film['note_violence'],
            film['note_sexe'], film.get('note_complexite', 0.0), film.get('note_language', 0.0), film.get('note_drogue', 0.0), film.get('note_utilisateur', 0.0),
            film.get('age_interdit', 0.0), film.get('age_recommande', 0.0), film.get('realisateur', ''), film.get('scenariste', ''),
            film.get('duration', 0.0), img_path
        )
    )
conn.commit()
conn.close()
